listsites:
  sites:
    -
      url: http://www.playback.ru
      name: playback
    -
      url: https://ipfran.ru
      name: Ipfran
    -
      url: http://radiomv.ru
      name: Radiomv
    -
      url: https://volochek.life
      name: Volochek
    -
      url: https://dimonvideo.ru
      name: Dimonvideo
    -
      url: https://nikoartgallery.com
      name: Nikoartgallery
    -
      url: https://et-cetera.ru
      name: Et-Cetera
    -
      url: https://www.lutherancathedral.ru
      name: Lutherancathedral
    -
      url: https://dombulgakova.ru
      name: Dombulgakova
    -
      url: https://www.svetlovka.ru
      name: Svetlovka

useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
referrer: http://www.google.com

spring.datasource.url: jdbc:mysql://localhost:3306/search_engine
spring.datasource.username: root
spring.datasource.password: hWN-h2z-aPE-8dQ
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false

